# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
#

name: "Dependency Review"
on: [pull_request]
permissions:
  contents: read
jobs:
  dependency-review:
    runs-on: employ-self-hosted
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Dependency Review
        uses: actions/dependency-review-action@67d4f4bd7a9b17a0db54d2a7519187c65e339de8 # v4
        with:
          fail-on-severity: critical
          fail-on-scopes: runtime, development
